version: '3'

services:
  laravel_backend:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    volumes:
      - ./laravel:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app_network
    
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - LOG_CHANNEL=stack
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
      - DB_CONNECTION=mysql
      - DB_HOST=mysql_database  # Cambia esta línea para que apunte al servicio MySQL
      - DB_PORT=3306
      - DB_DATABASE=cinema
      - DB_USERNAME=root
      - DB_PASSWORD=
      # Agrega aquí el resto de las variables de entorno relacionadas con tu configuración .env de Laravel
    depends_on:
      - mysql_database

  nuxt_frontend:
    build:
      context: ./nuxt
      dockerfile: Dockerfile
    volumes:
      - ./nuxt:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - app_network

  mysql_database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: cinema
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
